// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DatabaseLibrary.Models
{
    public partial class CustomerSequence
    {
        public int Id { get; set; }
        public int? CustomerIdentifier { get; set; }
        public string CurrentSequenceValue { get; set; }
        public string SequencePreFix { get; set; }

        public virtual Customers CustomerIdentifierNavigation { get; set; }
    }
}